# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'dokcerHub'
      repository: 'shukiyahu/echo_ex'
      command: buildAndPush
      Dockerfile: '**/Dockerfile'
      tags: 1.0.$(Build.BuildId)

# - job: Push
#   dependsOn: Build
#   steps:
#   - task: Docker@2
#     inputs:
#       containerRegistry: 'dokcerHub'
#       repository: 'shukiyahu/echo_ex'
#       command: 'push'
#       tags: $(Build.BuildNumber)
